{
 "title": "dbpooltest",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Request rate (ops avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(method, uri) (irate(http_server_requests_seconds_count {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Method Response times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by(method, instance) (rate(method_timed_seconds_sum {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\"}[1m]))* 1000  / sum by(method, instance) (rate(method_timed_seconds_count {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\"}[1m]))",
     "legendFormat": "{{method}} {{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum  by (instance) (jvm_threads_daemon{instance=\"172.18.0.4:8080\",job=\"spring_micrometer\"})",
     "legendFormat": "Daemon {{ instance }}"
    },
    {
     "expr": "sum by (instance) (tomcat_threads_current{instance=\"172.18.0.4:8080\",job=\"spring_micrometer\"})",
     "legendFormat": "Tomcat {{ instance }}"
    },
    {
     "expr": "sum by (instance) (tomcat_threads_busy{instance=\"172.18.0.4:8080\",job=\"spring_micrometer\"})",
     "legendFormat": "Tomcat {{ instance }}"
    }
   ]
  },
  {
   "title": "Heap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{area=\"heap\",instance=\"172.18.0.4:8080\",job=\"spring_micrometer\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum by (instance) (jvm_memory_max_bytes{area=\"heap\",instance=\"172.18.0.4:8080\",job=\"spring_micrometer\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Response times (ms)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_seconds_sum {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\"}[1m])) * 1000 / sum (rate(http_server_requests_seconds_count {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Usage (millicores)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(system_cpu_usage{instance=\"172.18.0.4:8080\",job=\"spring_micrometer\"}) by (service, instance)  * 1000",
     "legendFormat": "{{service}} {{instance}}"
    }
   ]
  },
  {
   "title": "DB Connection pool times - READ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(hikaricp_connections_usage_seconds_sum {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\", pool=\"hikariREAD\"}[1m]) * 1000) / sum (rate(hikaricp_connections_usage_seconds_count {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\", pool=\"hikariREAD\"}[1m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum (rate(hikaricp_connections_acquire_seconds_sum {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\", pool=\"hikariREAD\"}[1m]) * 1000) / sum (rate(hikaricp_connections_acquire_seconds_count {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\", pool=\"hikariREAD\"}[1m]))",
     "legendFormat": "Aquire"
    },
    {
     "expr": "sum (rate(hikaricp_connections_creation_seconds_sum {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\", pool=\"hikariREAD\"}[1m]) * 1000) / sum (rate(hikaricp_connections_creation_seconds_count {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\", pool=\"hikariREAD\"}[1m]))",
     "legendFormat": "Creation"
    }
   ]
  },
  {
   "title": "DB Connection pool times - WRITE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(hikaricp_connections_usage_seconds_sum {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\", pool=\"hikariWRITE\"}[1m]) * 1000) / sum (rate(hikaricp_connections_usage_seconds_count {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\", pool=\"hikariWRITE\"}[1m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum (rate(hikaricp_connections_acquire_seconds_sum {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\", pool=\"hikariWRITE\"}[1m]) * 1000) / sum (rate(hikaricp_connections_acquire_seconds_count {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\", pool=\"hikariWRITE\"}[1m]))",
     "legendFormat": "Aquire"
    },
    {
     "expr": "sum (rate(hikaricp_connections_creation_seconds_sum {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\", pool=\"hikariWRITE\"}[1m]) * 1000) / sum (rate(hikaricp_connections_creation_seconds_count {instance=\"172.18.0.4:8080\",job=\"spring_micrometer\", pool=\"hikariWRITE\"}[1m]))",
     "legendFormat": "Creation"
    }
   ]
  },
  {
   "title": "Database Connection Pool - READ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (hikaricp_connections_active{instance=\"172.18.0.4:8080\",job=\"spring_micrometer\" , pool=\"hikariREAD\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum (hikaricp_connections_idle{instance=\"172.18.0.4:8080\",job=\"spring_micrometer\", pool=\"hikariREAD\"})",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Database Connection Pool - WRITE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (hikaricp_connections_active{instance=\"172.18.0.4:8080\",job=\"spring_micrometer\", pool=\"hikariWRITE\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum (hikaricp_connections_idle{instance=\"172.18.0.4:8080\",job=\"spring_micrometer\", pool=\"hikariWRITE\"})",
     "legendFormat": "Idle"
    }
   ]
  }
 ]
}